<?php
// Copyright 2026 Airpay Payment Services
// License http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later

/**
 * Plugin version — Sentientia LMS AI Quiz Generation.
 *
 * Stream G (Tier 1 #4) — Course Authors paste source content (SCORM
 * transcripts, narration text, uploaded SOPs) and request a quiz
 * draft generated by Anthropic Claude. Every generated draft passes
 * through a mandatory human-review gate (approve / edit / reject)
 * before the approved questions are pushed to a `mod_quiz` activity.
 *
 * The plugin ships disabled. Even when the feature flag is ON, every
 * call to the Anthropic API is gated behind a [CONFIRM] step because
 * Anthropic billing is per-token. The first MVP run is deliberately
 * single-tenant (Airpay customer-zero) — multi-customer prompt
 * versioning + cost-quota work lands in v0.2.0.
 *
 * Roadmap
 *  - G.0  MVP — scaffold + DB schema + feature flag + generate + review
 *  - G.1  Per-customer prompt overrides + Hindi quiz generation
 *  - G.2  PDF upload pipeline (admin pastes -> upload SOP -> extract -> generate)
 *  - G.3  Cost analytics dashboard + per-customer token quota
 *  - G.4  Mod_quiz push — convert approved questions into a real quiz activity
 *  - G.5  Auto-suggest quiz placement (which course chapter a draft belongs to)
 *
 * @package    local_sentientia_aiquiz
 * @copyright  2026 Airpay Payment Services
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$plugin->component = 'local_sentientia_aiquiz';
// 2026-05-24 G.0 — MVP scaffold. Schema + feature flag + Anthropic
// client (curl-based) + prompt builder + response parser + generate UI
// + review UI + mod_quiz push stub + Hindi pack + ADR-012.
$plugin->version   = 2026052400;
$plugin->requires  = 2022041900;
$plugin->maturity  = MATURITY_ALPHA;     // MVP — needs prod sign-off before flag flips
$plugin->release   = '0.1.0-alpha';
$plugin->dependencies = [
    'local_airpay_core' => 2026051401,   // feature_flags resolver + customer scope
];

// Release history
// 0.1.0-alpha  Phase G.0: MVP scaffold. Feature flag default OFF.
//              No live API calls without explicit per-call [CONFIRM].
