// Copyright 2026 Airpay Payment Services
// License http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later

/**
 * Sentientia LMS PWA — subscribe AMD module (Phase B.2.b).
 *
 * Drives the browser side of the push subscription flow:
 *   1. Detect Notification + PushManager + ServiceWorker support
 *   2. Read the current subscription state (subscribed / unsubscribed)
 *   3. On click → requestPermission → pushManager.subscribe → POST to WS
 *   4. On unsubscribe click → pushManager.unsubscribe → DELETE via WS
 *
 * The VAPID public key is injected via data-vapid-public-key on the
 * .sentientia-pwa-subscribe root element. The keypair is generated by
 * cli/generate_vapid_keys.php and stored in mdl_config_plugin.
 *
 * IMPORTANT: This source file is ES6 for clarity. The build/ version
 * MUST be ES5-compatible AND use a named define() — both constraints
 * were violated by the programs/classroom/learningpath plugins on
 * 2026-05-20 and broke every other AMD module sitewide for ~6 hours.
 * See PROJECT-STATE.md "AMD pipeline triple-bug fix" entry.
 *
 * @module     local_sentientia_pwa/subscribe
 * @copyright  2026 Airpay Payment Services
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

import Ajax from 'core/ajax';
import Notification from 'core/notification';

const ROOT_SELECTOR = '.sentientia-pwa-subscribe';
const BUTTON_ID = 'sentientia-pwa-subscribe-btn';

/**
 * Convert base64url string to Uint8Array — required by PushManager.subscribe()
 * applicationServerKey parameter.
 */
function urlBase64ToUint8Array(base64String) {
    const padding = '='.repeat((4 - base64String.length % 4) % 4);
    const base64 = (base64String + padding).replace(/-/g, '+').replace(/_/g, '/');
    const rawData = window.atob(base64);
    const outputArray = new Uint8Array(rawData.length);
    for (let i = 0; i < rawData.length; ++i) {
        outputArray[i] = rawData.charCodeAt(i);
    }
    return outputArray;
}

function isPushSupported() {
    return 'serviceWorker' in navigator
        && 'PushManager' in window
        && 'Notification' in window;
}

function setButtonState(button, state, labels) {
    if (!button) {
        return;
    }
    button.disabled = false;
    button.classList.remove('btn-primary', 'btn-outline-secondary', 'btn-secondary', 'btn-danger');

    if (state === 'subscribed') {
        button.textContent = labels.unsubscribe;
        button.dataset.action = 'unsubscribe';
        button.classList.add('btn-outline-secondary');
    } else if (state === 'unsubscribed') {
        button.textContent = labels.subscribe;
        button.dataset.action = 'subscribe';
        button.classList.add('btn-primary');
    } else if (state === 'unsupported') {
        button.disabled = true;
        button.textContent = labels.unsupported;
        button.classList.add('btn-secondary');
    } else if (state === 'permission_denied') {
        button.disabled = true;
        button.textContent = labels.denied;
        button.classList.add('btn-danger');
    }
}

function handleSubscribe(button, vapidKey, labels) {
    if (Notification.permission === 'denied') {
        setButtonState(button, 'permission_denied', labels);
        return;
    }
    Notification.requestPermission().then((permission) => {
        if (permission !== 'granted') {
            setButtonState(button, 'permission_denied', labels);
            return null;
        }
        return navigator.serviceWorker.ready
            .then((registration) => registration.pushManager.subscribe({
                userVisibleOnly: true,
                applicationServerKey: urlBase64ToUint8Array(vapidKey),
            }))
            .then((subscription) => {
                const sub = subscription.toJSON();
                const keys = sub.keys || {};
                return Ajax.call([{
                    methodname: 'local_sentientia_pwa_save_subscription',
                    args: {
                        endpoint: sub.endpoint,
                        p256dh: keys.p256dh || '',
                        authkey: keys.auth || '',
                        useragent: navigator.userAgent.substring(0, 250),
                    },
                }])[0];
            })
            .then(() => setButtonState(button, 'subscribed', labels));
    }).catch((err) => {
        setButtonState(button, 'unsubscribed', labels);
        Notification.exception(err);
    });
}

function handleUnsubscribe(button, labels) {
    navigator.serviceWorker.ready
        .then((registration) => registration.pushManager.getSubscription())
        .then((subscription) => {
            if (!subscription) {
                setButtonState(button, 'unsubscribed', labels);
                return null;
            }
            const endpoint = subscription.endpoint;
            return subscription.unsubscribe().then(() => {
                return Ajax.call([{
                    methodname: 'local_sentientia_pwa_delete_subscription',
                    args: {endpoint: endpoint},
                }])[0];
            });
        })
        .then(() => setButtonState(button, 'unsubscribed', labels))
        .catch((err) => {
            Notification.exception(err);
        });
}

function bindClick(button, vapidKey, labels) {
    button.addEventListener('click', (ev) => {
        ev.preventDefault();
        const action = button.dataset.action;
        button.disabled = true;
        if (action === 'subscribe') {
            handleSubscribe(button, vapidKey, labels);
        } else if (action === 'unsubscribe') {
            handleUnsubscribe(button, labels);
        }
    });
}

export const init = () => {
    const root = document.querySelector(ROOT_SELECTOR);
    if (!root) {
        return;
    }
    const button = document.getElementById(BUTTON_ID);
    if (!button) {
        return;
    }

    const labels = {
        subscribe: button.dataset.subscribeLabel || 'Enable notifications',
        unsubscribe: button.dataset.unsubscribeLabel || 'Disable notifications',
        unsupported: button.dataset.unsupportedLabel || 'Not supported',
        denied: button.dataset.deniedLabel || 'Notifications blocked',
    };

    if (!isPushSupported()) {
        setButtonState(button, 'unsupported', labels);
        return;
    }

    if (Notification.permission === 'denied') {
        setButtonState(button, 'permission_denied', labels);
        return;
    }

    const vapidKey = root.dataset.vapidPublicKey;
    if (!vapidKey) {
        setButtonState(button, 'unsupported', labels);
        return;
    }

    navigator.serviceWorker.ready
        .then((registration) => registration.pushManager.getSubscription())
        .then((existing) => {
            setButtonState(button, existing ? 'subscribed' : 'unsubscribed', labels);
            bindClick(button, vapidKey, labels);
        })
        .catch(() => {
            setButtonState(button, 'unsubscribed', labels);
            bindClick(button, vapidKey, labels);
        });
};
