<?php
// Copyright 2026 Airpay Payment Services
// License http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later

/**
 * Plugin version — Sentientia LMS AI Course Recommendations.
 *
 * Stream G (Tier 1 AI feature #5) — Learners see the top 3-5 personalised
 * course recommendations on their dashboard, generated by Anthropic Claude
 * from their completion history, current skill profile, role, and per-
 * tenant learning patterns. Every recommendation is logged with
 * reasoning so a learner can ask "why was this suggested?".
 *
 * Like its sibling `local_sentientia_aiquiz`, this plugin ships disabled.
 * Even when the master flag is ON, every Anthropic POST is gated behind
 * a per-call [CONFIRM] gate — for recommendations the gate lives in the
 * background cron task (admin must explicitly tick "send batch to
 * Anthropic" before the task POSTs). The deterministic mock client
 * lets the MVP be demoed end-to-end without spending money.
 *
 * Roadmap
 *  - H.0  MVP — scaffold + DB schema + feature flag + dashboard block
 *  - H.1  Per-customer prompt overrides + Hindi recommendation summaries
 *  - H.2  Cohort-based recommendations (recommend what peers completed)
 *  - H.3  Cost analytics dashboard + per-customer token quota
 *  - H.4  A/B recommendation strategies (collaborative vs LLM-only)
 *
 * @package    local_sentientia_recommendations
 * @copyright  2026 Airpay Payment Services
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

defined('MOODLE_INTERNAL') || die();

$plugin->component = 'local_sentientia_recommendations';
// 2026-05-25 H.0 — MVP scaffold. Schema + feature flag + Anthropic
// client (curl-based) + prompt builder + recommendation engine + mock
// pipeline + dashboard block + Hindi pack + ADR-015.
// 2026-08-05 — OPT-IN local_sentientia_ai gateway delegation in
// anthropic_client::generate() (ADR-028 Phase 2.3; routing switch
// sentientia.ai.gateway.enabled default OFF = byte- and side-effect-
// identical legacy path; mock passed down as callable; 'denied'→'failed').
$plugin->version   = 2026080500;
$plugin->requires  = 2022041900;
$plugin->maturity  = MATURITY_ALPHA;     // MVP — needs prod sign-off before flag flips
$plugin->release   = '0.1.1-alpha';
$plugin->dependencies = [
    'local_sentientia_platform'    => 2026051401,   // feature_flags resolver + customer scope
    'local_sentientia_courses' => 2026052003,   // course catalogue + completion
];

// Release history
// 0.1.0-alpha  Phase H.0: MVP scaffold. Feature flag default OFF.
//              No live API calls without explicit per-call [CONFIRM].
// 0.1.1-alpha  Sentientia AI gateway migration (opt-in, dormant by default).
//              All plugin-level gates unchanged.
