<?php
// Copyright 2026 Airpay Payment Services
// License http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later

/**
 * Feature flag registry for local_sentientia_authoring (GenAI Authoring Studio).
 *
 * Three flags, ALL default OFF per CLAUDE.md §13:
 *
 *  1. sentientia.authoring.enabled  — master switch. When OFF, every
 *                                      /local/sentientia_authoring/ page
 *                                      returns a feature-off exception and
 *                                      the nav link is hidden.
 *  2. sentientia.authoring.tts      — gates the TTS voiceover surface. When
 *                                      OFF, voiceover UI + jobs are hidden.
 *                                      When ON the voiceover studio runs, but
 *                                      audio is generated by the deterministic
 *                                      MOCK tts_client unless live_api is ALSO
 *                                      ON (and the per-call [CONFIRM] gate is
 *                                      ticked + an API key configured).
 *  3. sentientia.authoring.live_api — the single gate that lets ANY live
 *                                      external call (Anthropic course
 *                                      generation OR ElevenLabs TTS) actually
 *                                      leave the server. Default OFF → every
 *                                      generation/voiceover uses the mock
 *                                      client, zero cost, no credentials. ON
 *                                      only in production once a key is
 *                                      configured AND a human flips it AND the
 *                                      caller passes the per-action [CONFIRM]
 *                                      gate enforced in the UI layer.
 *
 * Mock-mode (live_api OFF) is what makes the whole studio demoable end to
 * end without spending money — the same discipline as local_sentientia_aiquiz
 * and local_sentientia_translate.
 *
 * @package local_sentientia_authoring
 */

defined('MOODLE_INTERNAL') || die();

$flags = [

    // ─── Sentientia category — GenAI Authoring Studio (Craft competitor) ──
    'sentientia.authoring.enabled' => [
        'default'     => false,
        'description' => 'Sentientia LMS GenAI Authoring Studio (gap P0.3 —
                          Invince Craft competitor). Master switch. When OFF,
                          /local/sentientia_authoring/ pages return a
                          feature-off exception and the navigation link is
                          hidden. When ON, Course Authors with the :generate
                          cap can turn a prompt / pasted Doc / PDF text into a
                          full microlearning course draft — every generation
                          still requires the per-action [CONFIRM] gate plus
                          sentientia.authoring.live_api=ON for a real Anthropic
                          call (otherwise the deterministic mock client runs).',
    ],

    'sentientia.authoring.tts' => [
        'default'     => false,
        'description' => 'TTS voiceover surface (productized Workstream-B
                          ElevenLabs pipeline). When OFF, the voiceover studio
                          and its DB jobs are hidden. When ON the voiceover UI
                          appears, but audio is produced by the deterministic
                          mock tts_client unless sentientia.authoring.live_api
                          is ALSO ON and a key is configured and the per-call
                          [CONFIRM] gate is ticked. Default OFF — voiceover is
                          opt-in and starts in mock mode.',
    ],

    'sentientia.authoring.live_api' => [
        'default'     => false,
        'description' => 'Live external-API gate. When OFF, EVERY generation
                          (Anthropic course draft) and EVERY voiceover
                          (ElevenLabs TTS) uses the deterministic mock client —
                          zero cost, no internet, no credentials. When ON, the
                          same code paths POST to api.anthropic.com /
                          api.elevenlabs.io using keys from the admin settings.
                          Companion flag sentientia.authoring.enabled must also
                          be ON. Mock-mode is the default so the MVP can be
                          demoed end-to-end without spending money.',
    ],

];
